"""
Author: Nguyen Tan Loc
Date: 22/10/2021
Problem:
 Draw a structure chart for one of the solutions to the programming projects of
Chapters 4 and 5. The program should include at least two function definitions
other than the main function.
Solution:
About Structured charts
 • Structured charts are the pictorial representations that show relationships and data transfers among the functions that are present in a program.
 • Each function is represented using a rectangular box that has its name inside it.
 • The relationship between these functions is described using lines that connect these functions.
 • The data type of the input being provided to the function and the output that is being generated by this function is labeled on the connecting lines.
 • Always the main function lies athe top of the structured chart.
    ....
"""